config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  devise_for :parents, controllers: {
  sessions: 'parents/sessions',
  registrations: 'parents/registrations'
}
  devise_for :sitters, controllers: {
  sessions: 'sitters/sessions',
  registrations: 'sitters/registrations'
}

  resources :calendars
  resources :parents
  resources :sitters
  resources :gigs
  resources :requests
  resources :notes

  post '/sitters/:id', to: 'parents#remove_sitter_from_parent'
  post '/parents/:id', to: 'parents#remove_sitter_from_parent'
  post '/requests/:id', to: 'gigs#request_to_gig'
  post '/gigs/gigs/:id', to: 'gigs#add_sitter_to_gig'

  authenticated :parent do
    root to: 'calendars#index'
  end

  authenticated :sitter do
    root to:'calendars#index'
  end

  root to: 'home#index'

end

app/models/sitter.rb
class Sitter < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_and_belongs_to_many :parents

after_create :build_calendar

  def build_calendar
    Calendar.create(user_id: self.id)
    # Associations must be defined correctly for this syntax, avoids using ID's directly.
  end

end

app/controllers/sitters/confirmations_controller.rb
class Sitters::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/sitters/omniauth_callbacks_controller.rb
class Sitters::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/sitters/passwords_controller.rb
class Sitters::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/sitters/registrations_controller.rb
class Sitters::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  private
    def sign_up_params
      params.require(:sitter).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:sitter).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
    end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/sitters/sessions_controller.rb
class Sitters::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/sitters/unlocks_controller.rb
class Sitters::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/sitters_controller.rb
class SittersController < ApplicationController

  def index
    @sitter = Sitter.find(params[:format])
    @requests = Request.all.where(sitter_email: @sitter.email).order('start_time ASC').where("start_time >= ?", Time.now - 24.hours)
    @notes = Note.all.where(sitter_id: @sitter.id)
  end

  def show
    @sitter = Sitter.find(params[:id])
    @requests = Request.all.where(sitter_email: @sitter.email).order('start_time ASC').where("start_time >= ?", Time.now - 24.hours)
    @gigs = Gig.all.where(sitter_id: current_sitter.id);
  end

  private

  def sitter_params
      params.require(:sitter).permit(:email, :password)
  end

end

app/helpers/sitters_helper.rb
module SittersHelper
end

app/views/sitters/index.html.erb
<div class="sitter-index">

  <div class="sitter-info">
    <h3>Sitter Info</h3>
    <% email = @sitter.email.split('@')[0] %>
    <h4> Email: <%= @sitter.email %> </h4>
  </div>

  <div class="remove-sitter-option">
    <%= link_to "Remove #{email.capitalize}", "/sitters/#{@sitter.id}", method: :post, class: 'remove-button right' %>
  </div>

  <div class="requested-sitters">
    <% if @requests.empty?%>
    <p> No current requests for <%=@sitter.email.split('@')[0]%> </p>
    <% else %>
      <h4> Requested for: </h4>
        <% @requests.each do |request| %>
          <br>
          <%= request.start_time.strftime("%B %d %I:%M %p") %> - <%= request.end_time.strftime("%I:%M %p") %>
          - $<%= request.cost %>
          <br>
          <%= link_to 'Delete Request', request_path(request), method: :delete, data: { confirm: "Are you sure you don't need them anymore? "} %>
        <% end %>
    <% end %>
  </div>

  <div class="request-form">
    <h4> Start New Request </h4>
    <%= form_with(model: Request.new, local: true) do |f| %>
    <br>
    <%= f.label "From", class: 'form-label' %>
    <%= f.datetime_select :start_time, :default => Time.now, ampm: true, discard_year: true %>
    <br>
    <%= f.label "Until", class: 'form-label' %>
    <%= f.datetime_select :end_time, :default => Time.now, ampm: true, discard_year: true %>
    <br>
    <%= f.label "Cost", class: 'form-label' %>
    <span>$<%= f.number_field :cost, :class=> "text-area" %></span>
    <%= f.hidden_field :sitter_email, :value => @sitter.email %>
    <br>
    <%= f.submit "Request #{email.capitalize}", :class=> "submit-button right"  %>
    <% end %>
    <br>
  </div>
  <div>
    <h3> Notes: </h3>
      <% @notes.each do |note| %>
      <ul class="note-list">
        <%= note.text %>
        <%= link_to '- remove', note_path(note), class: 'remove-note', method: :delete, data: { confirm: "Are you sure you don't need this anymore?"} if note.parent_id == current_parent.id %> </button>
      </ul>
      <% end %>
  </div>
  <div>
    <h3> Add New Note: </h3>
    <h5> Notes are anonymous, but please only leave helpful notes!</h5>
    <%= form_with(model: Note.new, local: true) do |f| %>
    <%= f.hidden_field :sitter_id, :value => @sitter.id %>
    <%= f.text_area(:text, size: '70x12', placeholder: "Add a note about this sitter.", :class=> "text-area") %>
    <%= f.submit "Add Note", :class=> "submit-button"  %>
    <% end %>
    <br>

  </div>

</div>

app/views/sitters/show.html.erb
<div class="sitter-show">

  <h3>Welcome to Your Sitter Profile, <%= @sitter.first_name %></h3>

  <h4> Email: <%= @sitter.email %> </h4>

  <div class="requested-sitters">
  <h4>Recent Gigs:</h4>
    <% if @gigs.empty?%>
      <p> You haven't had any recent babysitting jobs </p>
    <% else %>
      <% @gigs.each do |gig| %>
        <ul>
          <%= gig.start_time.strftime("%B %d @ %I:%M %p") %> for <%= Parent.where(id: gig.parent_id).last.first_name %>
        </ul>
      <% end %>
    <% end %>
  </div>

  <div class="requested-sitters">
    <h4>Requests:</h4>
    <% if @requests.empty?%>
      <p> You don't have any requests currently, <%=@sitter.email.split('@')[0]%> </p>
    <% else %>
      <p> You've been requested for: </p>
      <% @requests.each do |request| %>
        <div class="request">
          <br>
          <%= request.start_time.strftime("%B %d, %Y %I:%M %p") %> - <%= request.end_time.strftime("%B %d, %Y %I:%M %p") %>
          - $<%= request.cost %>
          <br>
          <% @parent = Parent.where(email: request.parent_email).last %>
          By: <%= link_to @parent.email, parents_path(@parent.id)  %>
          <br>
          <%= link_to 'View Request', request_path(request)  %>
          <br>
        </div>
      <% end %>
    <% end %>
  </div>

</div>