config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  devise_for :parents, controllers: {
  sessions: 'parents/sessions',
  registrations: 'parents/registrations'
}
  devise_for :sitters, controllers: {
  sessions: 'sitters/sessions',
  registrations: 'sitters/registrations'
}

  resources :calendars
  resources :parents
  resources :sitters
  resources :gigs
  resources :requests
  resources :notes

  post '/sitters/:id', to: 'parents#remove_sitter_from_parent'
  post '/parents/:id', to: 'parents#remove_sitter_from_parent'
  post '/requests/:id', to: 'gigs#request_to_gig'
  post '/gigs/gigs/:id', to: 'gigs#add_sitter_to_gig'

  authenticated :parent do
    root to: 'calendars#index'
  end

  authenticated :sitter do
    root to:'calendars#index'
  end

  root to: 'home#index'

end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :parent
  belongs_to :babysitter
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :check_for_users

  def index
    if current_parent
      @parent = current_parent
      @sitters = current_parent.sitters.all
      @gigs = Gig.where(parent_id: current_parent.id)
    else
      @sitter = current_sitter
      @parents = current_sitter.parents.all
      ids = @parents.pluck(:id)
      @gigs = Gig.all.where(parent_id: ids)
    end

  end


private

def parent_params
  params.require(:parent).permit(:email, :sitter_ids)
end

def sitter_params
  params.require(:sitter).permit(:email, :parent_ids)
end

end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/index.html.erb
<% @current_time = Time.new %>
<% @today = @current_time.day %>
<% @this_month = @current_time.month %>
<!-- parent views -->
<% if current_parent %>

<div class="page">

  <div class="calendar">
    <%= month_calendar events: @gigs do |date, gigs| %>
    <% @date_month = date.month %>
    <% @date_day = date.day %>
      <div class="cal-day <%= 'current-day' if @date_day == @today && @date_month == @this_month %> <%= 'not-current-month' if @date_month != @this_month %> "> <%= date.day %>
        <br>
        <% gigs.each do |gig| %>
          <% if gig.sitter_id.nil? %>
            <div class="open gig-status">
              <% @gig_time = gig.start_time.strftime("%I:%M") %>
              <% if @gig_time.split('')[0] == "0" %>
                <%= link_to @gig_time.slice(1,@gig_time.length), gig_path(gig) %>
              <% else %>
                <%= link_to @gig_time, gig_path(gig) %>
              <% end %>
            </div>
          <% else %>
          <% @gig_sitter = Sitter.where(id: gig.sitter_id).last %>
            <div class="taken gig-status">
              <% @gig_time = gig.start_time.strftime("%I:%M") %>
              <% if @gig_time.split('')[0] == "0" %>
                <%= link_to @gig_time.slice(1,@gig_time.length), gig_path(gig) %>
              <% else %>
                <%= link_to @gig_time, gig_path(gig) %>
              <% end %>
              - <%= link_to @gig_sitter.email.split('@')[0], sitters_path(@gig_sitter.id)  %>
            </div>
          <% end %>
        <% end %>
      </div>

    <% end %>
  </div>

  <div class="sitter-box">
    <br>
    <div class="client-box">
        <button class="babysitter-button" style="border:1px solid black; background-color: #c40f64;"><%= link_to 'Add Babysitting Gig', new_gig_path %></button>
        <button class="babysitter-button" style="border:1px solid black; background-color: #c40f64;"><%= link_to 'Add New Sitter', @parent %> </button>
        <button class="babysitter-button" style="border:1px solid black; background-color: #c40f64;"><%= link_to 'View My Profile', parent_path(@parent) %></button>
        <br>
      <h3>Your babysitters:</h3>
        <div class="babysitter-list">
          <% if @sitters.empty? %>
            <p> No sitters yet. </p>
          <% else %>
            <% @sitters.each do |sitter| %>
              <ul>
                <%= link_to sitter.email, sitters_path(sitter) %>
              </ul>
              <% end %>
          <% end %>
        </div>
    </div>
  </div>

</div>


<% else %>

<!-- Sitter Views -->
  <div class="page">

    <% @current_time = Time.new %>

    <%= month_calendar events: @gigs do |date, gigs| %>
    <% @date_month = date.month %>
    <% @date_day = date.day %>
      <div class="cal-day <%= 'current-day' if @date_day == @today && @date_month == @this_month %> <%= 'not-current-month' if @date_month != @this_month %> "> <%= date.day %>
        <br>
        <% gigs.each do |gig| %>
        <% @gig_parent = Parent.where(id: gig.parent_id).last %>
        <% @parent_email = @gig_parent.email.split('@')[0]%>
        <% @gig_time = gig.start_time.strftime("%I:%M") %>
          <% if gig.sitter_id.nil? %>
            <div class="open gig-status">
              <%= link_to @parent_email, parents_path(@gig_parent) %> -
              <% if @gig_time.split('')[0] == "0" %>
                <%= link_to @gig_time.slice(1,@gig_time.length), gig_path(gig) %>
              <% else %>
                <%= link_to @gig_time, gig_path(gig) %>
              <% end %>
            </div>
          <% elsif gig.sitter_id == current_sitter.id %>
            <div class="taken-by-you">
              <%= link_to @parent_email, parents_path(@gig_parent) %> -
              <% if @gig_time.split('')[0] == "0" %>
                <%= link_to @gig_time.slice(1,@gig_time.length), gig_path(gig) %>
              <% else %>
                <%= link_to @gig_time, gig_path(gig) %>
              <% end %>
            </div>
          <% else %>
            <div class="taken gig-status">
              <%= link_to @parent_email, parents_path(@gig_parent) %> -
              <% if @gig_time.split('')[0] == "0" %>
                <%= link_to @gig_time.slice(1,@gig_time.length), gig_path(gig) %>
              <% else %>
                <%= link_to @gig_time, gig_path(gig) %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>

    <% end %>

    <div class="non-calendar">
      <p><%= link_to 'My Profile', sitter_path(@sitter)%></p>
      <p>Signed in as: <%= @sitter.email %></p>
      <div class="client-box">
        <h4>Your clients: </h4>
        <% if @parents.empty? %>
          <p> No parents yet. </p>
        <% else %>
          <% @parents.each do |parent| %>
            <%= link_to parent.email, parents_path(parent), class: 'parent-emails' %>
            <br>
            <% end %>
        <% end %>
      </div>
    </div>

  </div>
<% end %>