config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  devise_for :parents, controllers: {
  sessions: 'parents/sessions',
  registrations: 'parents/registrations'
}
  devise_for :sitters, controllers: {
  sessions: 'sitters/sessions',
  registrations: 'sitters/registrations'
}

  resources :calendars
  resources :parents
  resources :sitters
  resources :gigs
  resources :requests
  resources :notes

  post '/sitters/:id', to: 'parents#remove_sitter_from_parent'
  post '/parents/:id', to: 'parents#remove_sitter_from_parent'
  post '/requests/:id', to: 'gigs#request_to_gig'
  post '/gigs/gigs/:id', to: 'gigs#add_sitter_to_gig'

  authenticated :parent do
    root to: 'calendars#index'
  end

  authenticated :sitter do
    root to:'calendars#index'
  end

  root to: 'home#index'

end

app/models/gig.rb
class Gig < ApplicationRecord
  validates :cost, presence: true

  validate :start_must_be_before_end_time

  private

  def start_must_be_before_end_time
   errors.add(:start_time, "must be before end time") unless
      start_time < end_time
  end

end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  def index
    @gigs = Gig.all
  end

  def show
    @gig = Gig.find(params[:id])
  end

  def new
    @gig = Gig.new
  end

  def create
    @gig = Gig.create(gig_params)
    @gig.parent_id = current_parent.id
    @gig.description = 'No details' if @gig.description == ""
    @gig.name = 'Babysitting' if @gig.name == ""

    if @gig.save
      redirect_to @gig
    else
      redirect_to new_gig_path, notice: @gig.errors.full_messages.each
    end
  end

  def request_to_gig
    @request = Request.find(params[:id])
    parent = Parent.where(email: @request.parent_email).last
    @gig = Gig.create(
      parent_id: parent.id,
      sitter_id: current_sitter.id,
      name: nil,
      start_time: @request.start_time,
      end_time: @request.end_time,
      cost: @request.cost,
      description: 'No details',
    )
    if @gig.save
      redirect_to '/'
    else
      redirect_to @request, notice: @gig.errors.full_messages.each
    end
  end


  def add_sitter_to_gig
    gig = Gig.find(params[:id])

    if gig.sitter_id.nil?
      gig.sitter_id = current_sitter.id
    else
      gig.sitter_id = nil
    end

    if gig.save
      redirect_to '/'
    else
      redirect_to gig_path(gig)
    end
  end

  def edit
    @gig = Gig.find(params[:id])
  end

  def update
    @gig = Gig.find(params[:id])
    if @gig.update(gig_params)
      redirect_to @gig
    else
      render 'edit'
    end
  end

  def destroy
    gig = Gig.find(params[:id])
    gig.destroy

    redirect_to '/'
  end

  private

  def gig_params
      params.require(:gig).permit(:name, :start_time, :end_time, :description, :cost, :parents_ids, :sitter_ids)
  end

end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/views/gigs/edit.html.erb
<div id="gig-new">
  <h3>Update Gig Info:</h3>
  <div></div>
  <div class="new-gig">
    <%= form_with(model: @gig, local: true) do |f| %>
    <%= f.label "Name " %>
    <br>
    <%= f.text_field :name, placeholder: @gig.name, class: 'text-area'  %>
    <br>
    <%= f.label "From" %>
    <br>
    <%= f.datetime_select :start_time, :default => Time.now, ampm: true, use_short_month: true, discard_year: true %>
    <br>
    <%= f.label "Until" %>
    <br>
    <%= f.datetime_select :end_time, :default => Time.now, ampm: true, use_short_month: true, discard_year: true %>
    <br>
    <%= f.label "Description", class: 'form-label' %>
    <br>
    <%= f.text_area(:description, size: '60x12', placeholder: "Add any babysitting details you'd like! \n\n Dinner instructions? \n\n Allergies? \n\n Bedtimes? \n\n Your kid's current favorite game? \n\n Perks for the babysitter? ", class: 'text-area') %>
    <br>
    <%= f.label "Cost" %>
    <br>
    <span>$<%= f.number_field :cost, class: 'text-area'  %></span>
    <br>
    <br>
    <%= f.submit 'Update', :class=> "submit-button" %>
    <% end %>
  </div>


</div>

app/views/gigs/new.html.erb
<div id="gig-new">
  <h3>Add your information below:</h3>
  <div></div>
  <div class="new-gig">
    <%= form_with(model: @gig, local: true) do |f| %>
    <%= f.label "Name " %>
    <br>
    <%= f.text_field :name, placeholder: 'Optional', class: 'text-area'  %>
    <br>
    <%= f.label "From" %>
    <br>
    <%= f.datetime_select :start_time, :default => Time.now, ampm: true, use_short_month: true, discard_year: true %>
    <br>
    <%= f.label "Until" %>
    <br>
    <%= f.datetime_select :end_time, :default => Time.now, ampm: true, use_short_month: true, discard_year: true %>
    <br>
    <%= f.label "Description", class: 'form-label' %>
    <br>
    <%= f.text_area(:description, size: '60x12', placeholder: "Add any babysitting details you'd like! \n\n Dinner instructions? \n\n Allergies? \n\n Bedtimes? \n\n Your kid's current favorite game? \n\n Perks for the babysitter? ", class: 'text-area') %>
    <br>
    <%= f.label "Cost" %>
    <br>
    <span>$<%= f.number_field :cost, class: 'text-area'  %></span>
    <br>
    <br>
    <%= f.submit 'Create Gig', :class=> "submit-button" %>
    <% end %>
  </div>


</div>

app/views/gigs/show.html.erb
<div class="gig-show" id="gig-show">
  <h2><%= @gig.name.nil? ? 'Gig: ' : @gig.name.capitalize + ': ' %>
    <small>
      <%= @gig.start_time.localtime.strftime("%B %d") %>
    </small>
  </h2>
  <%= link_to ' - Edit Details', edit_gig_path(@gig) if current_parent %>
  <%= link_to 'Claim This Gig?', "gigs/#{@gig.id}", method: :post if current_sitter %>
  <br>
  <br>
  <div class="gig-info">
    <h3>
      From:
    </h3>
    <p class="gig-info-items">
      <%= @gig.start_time.strftime("%I:%M %p") %></p>
    <h3>
      Until:
    </h3>
    <p class="gig-info-items"><%= @gig.end_time.strftime("%I:%M %p") %></p>
    <h3>
      Description:
    </h3>
    <% @gig.description.nil? ? @gig.description = 'no details' : @gig.description %>
    <p class="gig-info-items"><%= @gig.description %></p>
    <h3>
      Payment:
    </h3>
    <p class="gig-info-items">
      $<%= @gig.cost %></p>
  </div>

  <div class="status">
    <h3>
      Status:
    </h3>
    <% if @gig.sitter_id.nil? %>
    <p class="open gig-status">
      Open
    </p>
    <br>
  <% else %>
    <% if current_parent %>
    <p class="taken gig-status">
      Taken by
      <%= Sitter.where(id: @gig.sitter_id).last.email %>
    </p>
    <br>
    <% elsif @gig.sitter_id == current_sitter.id %>
    <p class="taken gig-status">
      Taken by you!
    </p>
    <br>
    <%= link_to 'Drop This Gig', "gigs/#{@gig.id}", method: :post if current_sitter %>
  <% else %>
    <p class="taken">
      Taken
    </p>
    <% end %>
    <% end %>
  </div>
  <%= link_to 'Delete This Gig', gig_path(@gig), class: 'remove-button', method: :delete, data: { confirm: "Are you sure you don't need this anymore?"}%>
</div>